openapi: 3.0.1
info:
  title: Genesis Config Generator
  description: '
  This API  provides the ability to generate various device configurations.
  '
  version: 1.0.0
servers:
  - url: 'lb.cbaxterjr.com'
paths:
  /api/v1/gcg:

    post:
      tags:
        - Genesis Config Generator(GCG)
      summary: Generates Base Configurations.
      description: '
      Creates Base Configurations based on the node_type key.
      '
      parameters:
        - in: query
          description: Type Configuration that you would to be generated
          name: template_type
          schema:

            type: string
            enum:
              - ios_base_node
              - linux_netplan_base

        - in: query
          description: Return Val type, default is text.
          name: return_type
          schema:
            type: string
            enum:
              - text
              - list
              - json

        - in: query
          description: Option to store to AWS cloud.
          name: store_aws
          schema:
            default: false
            type: boolean

        - in: query
          description: Return Val type, default is text.
          name: lab_name
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  description: The body is the schema based on the template_type selected.
                  type: val

      responses:
        '200':
          description: OK

tags:
  - name: Config

components:
  schemas:
    BaseConfig:
      $ref: 'openapi/schemas/ios_base_node.yml#/BaseConfig'
    LinuxNetplanBase:
      $ref: 'openapi/schemas/linux_netplan.yml#/LinuxNetplanBasic'